export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const FETCH_GITHUB_REPO = "FETCH_GITHUB_REPO";
export const FETCH_GITHUB_REPO_SUCCESS = "FETCH_GITHUB_REPO_SUCCESS";
export const FETCH_GITHUB_REPO_FAILURE = "FETCH_GITHUB_REPO_FAILURE";
